name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install alsa
      run: sudo apt-get -y install libasound2-dev
    - name: Create dummy music dir
      run: mkdir music
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
